### ISSUE TITLE
Can i use this library with BME680 instead of BME688 ?

### ISSUE THREAD

**Issue by yassineghzaiel9** [boschsensortec/Bosch-BSEC2-Library#19]
Hi, I wonder if it's possible to work with BME680 sensor instead BM688 , Is BSEC2 Library supports BME680 gas sensor ??

**Comment by neffs** [comment]
This is from the 2.4.0.0 release notes, available on the Bosch Sensortec website: 
`Unified static library to support sensor variants, Configuration files offered separately for BME680 and BME688 sensors.`.

→ Yes, but only after this repo is updated to 2.4.

**Comment by BST-Github-Admin** [comment]
@yassineghzaiel9 , it is supported now, however not recommended.

**Comment by Deepak-Mvk** [comment]
This issue is being closed, please re-open if you need any further clarifications.
