### ISSUE TITLE
Configuration files missing in repo (e.g. supply voltage configuration)

### ISSUE THREAD

**Issue by neffs** [boschsensortec/Bosch-BSEC2-Library#20]
The [official download of BSEC](https://www.bosch-sensortec.com/software-tools/software/bsec/) includes several configuration files, e.g. "bme688_sel_33v_300s_4d".

It would be helpful to have all of these included in this repository, to be able reference them directly in open source projects (e.g. ESPHome).
According to documentation the default is based on a 1.8V supply voltage, whereas most community projects probably use 3.3V. Without using a configuration file the heater settings are most likely wrong.

**Comment by Deepak-Mvk** [comment]
hi @neffs yes we can include all the configurations from [Website release](https://www.bosch-sensortec.com/software-tools/software/bsec/) in this repository. We will plan this during the upcoming update.

**Comment by dremsol** [comment]
@Deepak-Mvk do you have any release information about the upcoming update?

**Comment by Rudd-O** [comment]
Cna this please be merged?

**Comment by neffs** [comment]
Already included in v1.7.2502
