### ISSUE TITLE
DEMO_DATALOGGER_MODE == DEMO_RECORDING_MODE  ?

### ISSUE THREAD

**Issue by cpietsch** [boschsensortec/Bosch-BSEC2-Library#25]
The DEMO_DATALOGGER_MODE and DEMO_BLE_STREAMING_MODE is mentioned in the [readme](https://github.com/boschsensortec/Bosch-BSEC2-Library/blob/master/examples/bme68x_demo_sample/Quick_Start_Guide.md) but the statics in [code](https://github.com/boschsensortec/Bosch-BSEC2-Library/blob/master/examples/bme68x_demo_sample/bme68x_demo_sample.ino#L324) are DEMO_RECORDING_MODE and DEMO_TEST_ALGORITHM_MODE

Is the readme or the code outdated ?

**Comment by Deepak-Mvk** [comment]
Hi @cpietsch thank you pointing this out. We have addressed this in the new release.
