### ISSUE TITLE
EDK_DATALOGGER_LOG_FILE_ERROR

### ISSUE THREAD

**Issue by AndreaZGuz** [boschsensortec/Bosch-BSEC2-Library#29]
When executing the sketch, the module starts the sampling process but the reading process stops even before the FILE_SIZE_LIMIT is reached.
The file opens, executes the reading, and saves the data, cyclically. But there is a moment when the file can not be opened anymore, then the EDK_DATALOGGER_LOG_FILE_ERROR is triggered. 
The size of the final file saved into the SD card is not the same with every execution, it is from 60KB up to 193KB (too much smaller than the established limit).
We are using:

- ESP-WROOM-32 board
- BME688 sensor (eight-sensor module) (battery included)
- No changes made in the main sketch (bme68x_demo_sample example), we have only changed the PIN_SD_CS to allow the SPI communication with the SD card.

We would be grateful to receive your support.

**Comment by Deepak-Mvk** [comment]
2) Hi @AndreaZGuz this has been tested with the BME688 development kit and works fine. In your case it may not be the problem with the size limit but something else. Can you please share the steps to reproduce this issue.
