### ISSUE TITLE
example "multi" for Bsec2

### ISSUE THREAD

**Issue by huggymann** [boschsensortec/Bosch-BSEC2-Library#3]
Hello, could you please make an example for reading multiple bME688 at a time? I hoped the X8 board would do it, but it does read only 1 sensor after the MUX.

**Comment by huggymann** [comment]
Hello any comments here?

**Comment by huggymann** [comment]
This example could be based on the X8 board. There is an example for X8 board already, which is only reading 1 selectable sensor from the board. But the intention would be with 8 sensors, to read them all :)

**Comment by huggymann** [comment]
any news on the multiple readout example?

**Comment by BST-Github-Admin** [comment]
Hi @huggymann , this will be added in the next release, where we will also include multi-instance BSEC support.

**Comment by Deepak-Mvk** [comment]
Hi @huggymann the multi instance BSEC demonstration is part of [this release](https://github.com/boschsensortec/Bosch-BSEC2-Library/releases/tag/v1.5.2400).
